-- AlterTable
ALTER TABLE "GameSession" ALTER COLUMN "durationMs" DROP DEFAULT,
ALTER COLUMN "acquiredOT" DROP DEFAULT,
ALTER COLUMN "acquiredYT" DROP DEFAULT,
ALTER COLUMN "foulsCount" DROP DEFAULT;
